### PR TITLE
Handle send error

### LINKED ISSUE #27: SocketIO: Lots of panics on unwrap in case of there are lots of clients
error:
```
panicked at '14called `Result::unwrap()` on an `Err` value: PoisonError { .. }
', thread 'socketioxide/src/ns.rstokio-runtime-worker:' panicked at '104called `Result::unwrap()` on an `Err` value: PoisonError { .. }:', 14socketioxide/src/ns.rs
:104:14
```
How to reproduce:
run socketio server(i used main) `cargo run --release --bin socketioxide-e2e`
run js clients [client.zip](https://github.com/Totodore/socketioxide/files/11797832/client.zip)

For me it reproduces even with 100 clients.

also I locally tried to replace RWlock<Hashmap> to Dashmap and errors dissappear

### PR DESCRIPTION
**Pull request by biryukovmaxim**
use closure to handle fullchannel error, test checking it
resolves #27

### CODE REVIEW

**Comment by biryukovmaxim** [comment]
@Totodore that's a solution, but I put one todo, in case of error appears in binary payload send, will fix it when have  time

**Comment by biryukovmaxim** [comment]
@Totodore Done. should we mention how many packets remaining inside of the closure?
I think it's mandatory to mention in documentation, that event is successfully delivered if there is no errors, and that resend closure can send some parts

**Comment by biryukovmaxim** [comment]
Also I added dependency to easily implement Debug for Errors including closure
Maybe It's better to implement it manually without unnecessary dependencies, isn't it?

**Review by Totodore — CHANGES_REQUESTED** [review]
I really like the idea of the closure, I didn't considered this solution before you proposed it but it is very elegant.

File: socketioxide/src/errors.rs [hunk 1]
```diff
@@ -42,4 +50,42 @@ pub enum AckError {
...
+
+/// Error type for ack responses
+#[derive(Derivative)]
+#[derivative(Debug)]
+#[derive(thiserror::Error)]
+pub enum SendError {
+    #[error("sent to full socket chan, sid: {sid}")]
+    SocketFull {
+        sid: Sid,
+        #[derivative(Debug = "ignore")]
```
[the remark this answers is not in the document]
Comment (biryukovmaxim) [reply socketioxide/src/errors.rs:84]: Sure

**Comment by biryukovmaxim** [comment]
@Totodore in the last commit I replaced closure with Retryer struct. What do you think about that?

File: socketioxide/src/socket.rs [hunk 2]
```diff
@@ -350,20 +352,24 @@ impl<A: Adapter> Socket<A> {
...
             PacketData::BinaryEvent(_, ref mut bin, _) | PacketData::BinaryAck(ref mut bin, _) => {
                 std::mem::take(&mut bin.bin)
             }
             _ => vec![],
         };
+        let sender: Sender<EnginePacket> = self.tx.clone();
+        let packet = packet.try_into()?;
+        Retryer::new(
+            self.sid,
+            sender.clone(),
```
Comment (Totodore) [inline socketioxide/src/socket.rs:366]: I think it would be much better to only spawn a retryer when there is a failure, it would avoid a useless tx clone :
```rust
    match self.tx.try_send(packet) {
            Ok(()) => Ok(()),
            Err(TrySendError::Closed(_)) => todo!(),
            Err(TrySendError::Full(packet)) => Err(RetryerError::Remaining(Retryer::new(
                self.sid,
                self.tx.clone(),
                Some(packet),
                payload.into(),
            )).into()),
        }
```

File: socketioxide/src/retryer.rs [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+
+// todo bin payload and payload should be in one VecDeque,
+// todo sender should be the same for both types of SendPacket
+
+/// The `Retryer` struct represents a retry mechanism for sending packets.
+#[derive(Debug)]
+pub struct Retryer<T: Debug> {
+    sid: Sid,
+    sender: Sender<T>,
+    packet: Option<T>,
```
Comment (Totodore) [inline socketioxide/src/retryer.rs:14]: You could remove the generic param, only a `Sender<SendPacket>` is needed, it avoids one more clone

File: socketioxide/src/errors.rs [hunk 4]
```diff
@@ -42,4 +45,56 @@ pub enum AckError {
...
+    #[error("Error serializing JSON packet: {0:?}")]
+    Serialize(#[from] serde_json::Error),
+    /// An error occurred during the retry process in the `Retryer`.
+    #[error("Send error: {0:?}")]
+    RetryerError(#[from] RetryerError<SendPacket>),
+}
+
+/// Error type for the `Retryer` struct indicating various failure scenarios during the retry process.
+#[derive(thiserror::Error, Debug)]
+pub enum RetryerError<T: Debug> {
```
Comment (Totodore) [inline socketioxide/src/errors.rs:93]: You don't need any Generic, you can just have `SendPacket`

**Review by Totodore — CHANGES_REQUESTED** [review]
The retryer way is better, I like it

File: socketioxide/src/socket.rs (hunk 2 above)
Comment (biryukovmaxim) [reply socketioxide/src/socket.rs:366]: but also it force to have almost the same code in two places, it will be harder to maintain changes of sending logic

File: socketioxide/src/retryer.rs (hunk 3 above)
Comment (biryukovmaxim) [reply socketioxide/src/retryer.rs:14]: if you are sure that we don't use this retryer with another Packet, I'll remove it

File: socketioxide/src/errors.rs (hunk 4 above)
Comment (biryukovmaxim) [reply socketioxide/src/errors.rs:93]: same as the comment above

File: socketioxide/src/retryer.rs [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+
+    /// Retries sending the packet and binary payloads.
+    ///
+    /// # Returns
+    ///
+    /// - `Ok(())` if all packets were successfully sent.
+    /// - `Err(RetryerError)` if there are remaining packets to be sent or the socket is closed.
+    pub fn retry(mut self) -> Result<(), RetryerError<T>> {
+        // Retry sending the main packet
+        match self.packet.map(|p| self.sender.try_send(p)) {
```
Comment (Totodore) [inline socketioxide/src/retryer.rs:57]: Here you can do self.packet.take() to take the ownership of the packet.
You can then reuse the retryer in case of error whithout recreating one : 
```rust
self.packet = Some(packet);
return Err(RetryerError::Remaining(self))
```

**Review by Totodore — APPROVED** [review]
Merging

**Comment by Totodore** [comment]
One thing that it is important to note is that due to the possibility to retry to send binary packet it could lead to binary desynchronization. EngineIo binary packets have to be sent next to the event packet, so if there is a retry for a binary packet error and that between the original attempt and the retry there is another event packet sent it will break the mecanism.

**Comment by biryukovmaxim** [comment]
So I will think how to handle it. Looks like Socket should own buffer of failed messages to send them firstly or another Arc<Mutex> copy of retryer
